services:
  site:
    image: ruby:3.2
    working_dir: /site
    volumes:
      - .:/site
    ports:
      - "4000:4000"
      - "35729:35729"
    environment:
      JEKYLL_ENV: development
    command: >
      bash -lc "bundle install &&
      bundle exec jekyll serve --host 0.0.0.0 --port 4000 --livereload --livereload-port 35729"
